
services:   
 analysis-service: 
     build:
         context: analysis-services
     ports:
         - "8000:8000"
     stop_signal: SIGINT
     depends_on:
      - mongo
     networks:
         - generation-database

 transformation-service:
     build:
         context: transformation-services 
     ports:
         - "8001:8001"
     stop_signal: SIGINT
     networks:
         - pipeline-transformation
     
 logstash:
     build:
         context: logstash
     depends_on:
         - mongo
         - transformation-service
     networks:
         - pipeline-transformation
         - pipeline-output

 mongo: 
     image: mongodb/mongodb-community-server:6.0.10-ubi8
     ports:
         - "27017:27017"
     restart: always
     volumes:
         - mongodb_data:/data/db 
     networks:
         - generation-database
         - pipeline-output

 mongo-express:
     image: mongo-express:latest
     environment:
         - ME_CONFIG_BASICAUTH_USERNAME=admin
         - ME_CONFIG_BASICAUTH_PASSWORD=StrngP@ss123
         - ME_CONFIG_MONGODB_SERVER=mongo
         - ME_CONFIG_MONGODB_PORT=27017
     ports:
         - "8081:8081"
     depends_on:
         - mongo
     networks:
         - generation-database

networks:
    generation-database:
    pipeline-input:
    pipeline-transformation:
    pipeline-output:

volumes:
    mongodb_data:

     
   