services:
 analysis-service: 
     container_name: voir_analysis
     build:
         context: analysis-services
     depends_on:
      - mongo

 transformation-service:
     container_name: voir_transformation 
     build:
         context: transformation-services 
     depends_on:
         - mongo

 mongo: 
     image: mongodb/mongodb-community-server:6.0.10-ubi8
     restart: always
     environment:
         - MONGO_INITDB_ROOT_USERNAME=test
         - MONGO_INITDB_ROOT_PASSWORD=test 
     volumes:
         - type: bind
           source: ./data
           target: /data/db

 logstash:
     image: logstash:8.17.3 
     volumes:
         - ./logstash/config
     
   